name: 'Setup apptainer'
description: 'Setup apptainer'
author: 'I (@wx257osn2)'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "apptainer_version=v1.5.3" >> $GITHUB_ENV
        if [ ${{ runner.os }} != "Linux" ]; then
          echo "This action only supports Linux runner"
          exit 1
        fi
    - shell: bash
      run: |
        if [ ${{ runner.arch }} = "X64" ]; then
          download_arch="x86_64"
        elif [ ${{ runner.arch }} == "ARM64" ]; then
          download_arch="aarch64"
        fi
        curl -sSL https://github.com/wx257osn2/setup-apptainer/releases/download/${{ env.apptainer_version }}/ubuntu$(bash -c 'source /etc/os-release; echo ${VERSION_ID//./}')-${download_arch}.tar.zst | sudo tar -C /opt -x --use-compress-program="pzstd" -p --same-owner
    - shell: bash
      run: |
        echo "PATH=${PATH}:/opt/apptainer/bin" >> $GITHUB_ENV
