name: CI

on:
  push:
    tags: [ "v[1-9]*.[0-9]+.[0-9]+" ]

jobs:
  version-check:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v7
    - run: |
        tag=$(echo ${{ github.ref }} | sed 's@refs/tags/@@g')
        version_action=$(grep 'apptainer_version=v' action.yml | sed 's/ *echo "apptainer_version=\([^"]*\)" >> $GITHUB_ENV/\1/g')
        version_readme=$(grep 'uses: wx257osn2/setup-apptainer@v' README.md | sed 's|  - uses: wx257osn2/setup-apptainer@\([^ ]*\).*|\1|g')
        if [[ ${tag} != ${version_action} || ${tag} != ${version_readme} ]]; then
          echo "${tag} is not match with ${version}, you've forgotten bumping up!!"
          exit 1
        fi
  build:
    strategy:
      matrix:
        include:
          - image: ubuntu-24.04
            arch: x86_64
            ubuntu: ubuntu2404
          - image: ubuntu-24.04-arm
            arch: aarch64
            ubuntu: ubuntu2404
          - image: ubuntu-26.04
            arch: x86_64
            ubuntu: ubuntu2604
          - image: ubuntu-26.04-arm
            arch: aarch64
            ubuntu: ubuntu2604
    runs-on: ${{ matrix.image }}
    needs: version-check
    steps:
    - name: stop update man-page
      run: |
        echo "set man-db/auto-update false" | sudo debconf-communicate
        sudo dpkg-reconfigure man-db
    - uses: actions/checkout@v7
      with:
        repository: 'apptainer/apptainer'
        ref: ${{ github.ref_name }}
    - name: build
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libseccomp-dev libtalloc-dev libattr1-dev libprotobuf-c-dev libfuse3-dev zlib1g-dev liblzo2-dev liblz4-dev liblzma-dev libzstd-dev uuid-dev autoconf automake libtool pkg-config curl zstd patch
        ./mconfig -p /opt/apptainer --with-suid
        pushd ./builddir
        make -j $(nproc)
        make install
        popd
        mkdir -p deps
        ./scripts/download-dependencies ./deps
        rm ./deps/e2fsprogs*.tar.gz
        mkdir -p ./deps/e2fsprogs-e4f17380b2e5
        curl -fsSL https://github.com/wx257osn2/tytso-e2fsprogs/archive/e4f17380b2e5b8356ab9806689f780d386ce8e3e.tar.gz | tar -xz -C "./deps/e2fsprogs-e4f17380b2e5" --strip-component=1
        tar -czf "./deps/e2fsprogs-e4f17380b2e5.tar.gz" -C "./deps" "e2fsprogs-e4f17380b2e5"
        rm -r "./deps/e2fsprogs-e4f17380b2e5"
        pushd deps
        ../scripts/compile-dependencies .
        ../scripts/install-dependencies /opt/apptainer/libexec
        popd
        chmod 4755 /opt/apptainer/libexec/apptainer/bin/starter-suid
        sed -i 's/^#\? *alow setuid-mount squashfs = .*/allow setuid-mount squashfs = yes/' /opt/apptainer/etc/apptainer/apptainer.conf
        tar -C /opt -cf ./${{ matrix.ubuntu }}-${{ matrix.arch }}.tar.zst --use-compress-program="zstdmt -18" --owner=0 --group=0 --numeric-owner apptainer
    - id: check-tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[1-9][0-9]*\.[0-9]+\.[0-9]+$ ]]; then
          echo "deploy-needed=true" >> $GITHUB_OUTPUT
        fi
    - uses: actions/upload-artifact@v7
      if: steps.check-tag.outputs.deploy-needed == 'true'
      with:
        name: archive-${{ matrix.ubuntu }}-${{ matrix.arch }}
        path: ./${{ matrix.ubuntu }}-${{ matrix.arch }}.tar.zst
  deploy:
    runs-on: ubuntu-slim
    needs: build
    permissions:
      contents: write
    steps:
    - id: check-tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[1-9][0-9]*\.[0-9]+\.[0-9]+$ ]]; then
          echo "deploy-needed=true" >> $GITHUB_OUTPUT
        fi
    - parallel:
      - uses: actions/download-artifact@v8
        if: steps.check-tag.outputs.deploy-needed == 'true'
        with:
          name: archive-ubuntu2404-x86_64
      - uses: actions/download-artifact@v8
        if: steps.check-tag.outputs.deploy-needed == 'true'
        with:
          name: archive-ubuntu2404-aarch64
      - uses: actions/download-artifact@v8
        if: steps.check-tag.outputs.deploy-needed == 'true'
        with:
          name: archive-ubuntu2604-x86_64
      - uses: actions/download-artifact@v8
        if: steps.check-tag.outputs.deploy-needed == 'true'
        with:
          name: archive-ubuntu2604-aarch64
    - uses: softprops/action-gh-release@v3
      if: steps.check-tag.outputs.deploy-needed == 'true'
      with:
        files: |
          ubuntu2404-x86_64.tar.zst
          ubuntu2404-aarch64.tar.zst
          ubuntu2604-x86_64.tar.zst
          ubuntu2604-aarch64.tar.zst
